# Copyright 2026 The MathWorks, Inc.
description: Signal Processing Toolbox, DSP System Toolbox, Wavelet Toolbox, and DSP HDL Toolbox.
keywords:
  - matlab
  - signal-processing
  - dsp
  - audio
  - filtering
