# Copyright 2026 The MathWorks, Inc.
description: Data Acquisition Toolbox and Industrial Communication Toolbox.
keywords:
  - matlab
  - data-acquisition
  - instrument-control
  - industrial-communication
  - image-acquisition
  - vehicle-network
  - test-and-measurement
  - opcua
  - modbus
  - mqtt
  - aveva-pi
